blank_issues_enabled: false
contact_links:
  - name: ğŸ“– Documentation
    url: https://github.com/programmerjide/javadump/wiki
    about: Check our documentation for common questions
  - name: ğŸ’¬ Discussions
    url: https://github.com/programmerjide/javadump/discussions
    about: Ask questions and discuss ideas
  - name: â“ Stack Overflow
    url: https://stackoverflow.com/questions/tagged/javadump
    about: Get help from the community